#!/bin/bash

echo "📋 HANDMATIGE VERCEL DOMAIN SETUP"
echo "=================================="
echo ""
echo "Voer deze commands één voor één uit in je terminal:"
echo ""
echo "STAP 1: Install Vercel CLI"
echo "npm install -g vercel"
echo ""
echo "STAP 2: Login to Vercel"
echo "vercel login"
echo ""
echo "STAP 3: Link je project (als nog niet gedaan)"
echo "vercel link"
echo ""
echo "STAP 4: Add domains"
echo "vercel domains add www.bhv360.nl"
echo "vercel domains add bhv360.com"
echo "vercel domains add www.bhv360.com"
echo ""
echo "STAP 5: Check domains"
echo "vercel domains ls"
echo ""
echo "STAP 6: Deploy met nieuwe config"
echo "vercel --prod"
